### ISSUE TITLE
"hdiutil detach" times out on CircleCI

### ISSUE THREAD

**Issue by speleo3** [al45tair/dmgbuild#10]
The `hdiutil detach` step fails for me on [CircleCI](https://circleci.com/). Retrying several times, similar to [this pull request](https://bitbucket.org/al45tair/dmgbuild/pull-requests/11), fixes the issue (return code is 1 in my case, not 16).

Adding `-debug` to the call prints:

```
process_detach: entry with "/dev/disk1s1"
util_verify_dev_entry: entry with "disk1s1".
process_detach_deventry: about to unmount_and_eject disk1s1
unmount_and_eject(disk1s1)
LetDIDriverSettleDown: calling IOServiceWaitQuiet...
DI_kextWaitQuiet: about to call IOServiceWaitQuiet...
DI_kextWaitQuiet: IOServiceWaitQuiet took 0.000004 seconds
LetDiskImageDriverSettleDown: wait took 0.000070 seconds
hdiutil: detach: timeout for DiskArbitration expired
hdiutil: detach: drive not detached
```

**Comment by dbelcher** [comment]
Thank you @speleo3.  I was having a similar issue running dmgbuild from a script runner on TeamCity (with a build agent running macOS 10.14 Mojave).  Your PR fixed the issue.  I hope this PR can pass tests and get merged soon.
