### ISSUE TITLE
MacPorts: dmgbuild ports disappeared

### ISSUE THREAD

**Issue by fiee** [al45tair/dmgbuild#15]
Hi, I don’t know if you was involved in the ports for your project at all... Last week I tried to install [SCM Workbench](https://github.com/barry-scott/scm-workbench) and managed to do so using MacPorts Python 3.7. My MacPorts repository was a few weeks old. There were dmgbuild ports for all the Python versions. I first tried `py37-dmgbuild` and that failed, because the version of dmgbuild used for the ports was Python 2 only. (BTW you don’t tell anywhere which versions you support.) But the `py27-dmgbuild` port worked, and that was enough for me.
Today I wanted to document what I did for building, updated MacPorts – and there was no port for dmgbuild any more. I didn’t even find it mentioned in the [project](https://github.com/macports/macports-ports)’s commits.
Do you know anything? Whom to contact?

**Comment by fiee** [comment]
Ok, seems like the ports were only my imagination. MacPorts maintainers couldn’t find a trace. Probably I unconsciously used pip-3.7 and pip-2.7. Sorry for the noise.

**Comment by al45tair** [comment]
:-) Yeah. I'd rather work on top of vanilla Python, instead of messing about with fink/brew/ports. If you want Python versions other than the system one installed, I'd strongly recommend using pyenv rather than any of the package managers.

**Comment by fiee** [comment]
I tried to avoid installing yet another Python distribution. And MacPorts updates more or less automatically.
