### ISSUE TITLE
Not compatible with Python 3.9.0

### ISSUE THREAD

**Issue by al45tair** [al45tair/dmgbuild#24]
Not sure why, but dmgbuild works with Python 3.8, but not Python 3.9. I'm looking into it at the moment.

**Comment by al45tair** [comment]
OK, so the issue is that the upstream biplist package needs updating for Python 3.9. I might do something about that if its maintainer doesn't do something fairly sharp-ish.

**Comment by al45tair** [comment]
Aha. So in Python 3.4, plistlib gained support for binary plists, which means we don't even need biplist any more except on Python 2.7.16 (which Apple still ships).

I'll see what I can do about migrating dmgbuild (and friends) to the newer API.

**Comment by PatTheMav** [comment]
@al45tair Much appreciated - our macOS CI over on OBS has been failing since 3.9 became default in Homebrew it seems.. 😬

**Comment by al45tair** [comment]
Fixed in dmgbuild 1.4.1.
