### ISSUE TITLE
SetFile printing File Not Found errors when no files/extensions to hide are specified

### ISSUE THREAD

**Issue by PatTheMav** [al45tair/dmgbuild#25]
Thank you very much for fixing dmgbuild for newer Python versions, I however noticed the following errors happening locally as well as on CI using the same (old) settings.json to run `dmgbuild`:

```
ERROR: File Not Found. (-43)  on file: -a 
ERROR: File Not Found. (-43)  on file: E 
ERROR: File Not Found. (-43)  on file: -a 
ERROR: File Not Found. (-43)  on file: V 
```

From a quick look at the source it might be related to the new feature introduced in https://github.com/al45tair/dmgbuild/commit/e8056153abd3bdd83c4de2a44a6b0df8173d4741 - when nothing is specified to hide (i.e. the list is empty), `SetFile` is called without a file parameter.

Adding a simple guard (`if len(to_hide) > 0:`) seems to fix this issue. Also it doesn't seem to break the image creation process.

**Comment by al45tair** [comment]
Thanks for pointing this out. It seems /usr/bin/SetFile doesn't like it when there aren't any filenames. I've fixed it and released version 1.4.2.
