### ISSUE TITLE
Output from tool

### ISSUE THREAD

**Issue by fizzyade** [al45tair/dmgbuild#27]
Hi, I'm actually using this as part of my deployment script (I was using a different one which was hacky and relied on automation to open windows, move icons etc), as this directly writes the files it's perfect.

I am in the process of wrapping this up in an (Qt based) application, I have embedded python and the necessary modules and my application directly calls the builder from python (from c++) passing in a settings object.

My application works in one of 2 modes:

1.) It runs as a GUI application, in this you can add icons, shortcuts, background image etc, you drag the icons about and it uses opencv to analyse the background image for possible points of interest (where icons might snap to).  You can save a configuration file or hit build directly in the gui.

2.) It runs as a command line tool, you pass it a configuration file and it spits out the DMG exactly as you designed it in the GUI.

I am intending to add other items, like text place holders so that you can embed things like version numbers in the DMG background....and so on.

What I'm suffering with now is a lack of "output" for the script, it runs and either works or it doesn't, there's no status as the process goes on (i.e so I could have an "build" window which showed the progress of the task.

I'm wondering if maybe I should fork this and then add the necessary "hooks" into your module to that the progress status can be retrieved by my application and then send PR back to you if it's something that you might deem useful for others.

My app is GPLv3, and as soon as I've done a bit more tidying up I will make the repo public.

<img width="969" alt="CleanShot 2020-11-13 at 17 17 41@2x" src="https://user-images.githubusercontent.com/55795671/99101266-42dce780-25d4-11eb-960d-b2d2b1a3cb72.png">

**Comment by al45tair** [comment]
Qt seems a strange choice for a Mac app. It takes a bit of effort to make a Qt app seem like a proper native Mac app (Qt is pretty good, don't get me wrong; it's easily the best of the portable frameworks IMO), and it's very easy, as you've done here, to make something that looks like a Windows app with a smattering of Mac controls stuck on top.

Still, it's your program and it's up to you. I'd recommend learning Cocoa and building it with that instead. You can still use C++ if that's what floats your boat (though that'll be easier if you use Objective-C++ rather than Swift, otherwise you'll need a C interface that Swift can call through in order to get to your C++ code).

As regards status output, in principle I like the idea and if you were to submit a PR I'd certainly look at it.  In an ideal world, there would be three modes:

1. Quiet (i.e. as it is now). There should be a "-q" switch for this.
2. Interactive (formatted messages, suitable for end users). This should be the default.
3. Something machine-parseable (JSON would be a good choice, I think). This should be triggered by a switch.

Note that dmgbuild sometimes runs other programs to do its work; there might be a bit of fiddling to do around exactly what to do with the output from those programs.

**Comment by fizzyade** [comment]
> Qt seems a strange choice for a Mac app. It takes a bit of effort to make a Qt app seem like a proper native Mac app (Qt is pretty good, don't get me wrong; it's easily the best of the portable frameworks IMO), and it's very easy, as you've done here, to make something that looks like a Windows app with a smattering of Mac controls stuck on top.
> 
> Still, it's your program and it's up to you. I'd recommend learning Cocoa and building it with that instead. You can still use C++ if that's what floats your boat (though that'll be easier if you use Objective-C++ rather than Swift, otherwise you'll need a C interface that Swift can call through in order to get to your C++ code).
> 
> As regards status output, in principle I like the idea and if you were to submit a PR I'd certainly look at it. In an ideal world, there would be three modes:
> 
> 1. Quiet (i.e. as it is now). There should be a "-q" switch for this.
> 2. Interactive (formatted messages, suitable for end users). This should be the default.
> 3. Something machine-parseable (JSON would be a good choice, I think). This should be triggered by a switch.
> 
> Note that dmgbuild sometimes runs other programs to do its work; there might be a bit of fiddling to do around exactly what to do with the output from those programs.

Thanks for the response.

My rational is that I went with the ribbon bar specifically because it's a design paradigm that has successfully transferred from Windows to Mac (and not just through Microsoft designed tools, but via third party developers too) and it's something that people are familiar with and puts the controls right in front of you in a logical way.   I could remove the ribbon control and make it look 100% like a "standard cocoa app" but I think the usability of the tool would be worse for it.  As I sit here, I have a number of tools open none of which use a "standard Mac" interface, Affinity (Designer/Photo), CLion, Excel, VSCode, Logic Pro to name just a few, all of them have a custom UI that fits the Application rather than fitting the OS.

I am proficient in qt/mfc/windows sdk/.net/cocoa./swift/objective c/android dev as well, but with 25+ years of commercial software experience (both in Desktop CAD software and on embedded systems) I've come to the conclusion that writing variations of the same things over and over again in different languages and/or for different platforms is not a productive use of my time, which I why I tend to use Qt - even for single OS applications.

Of course this particular application is Mac only because of the reliance on tools such as hdiutil, I could however invest time in writing code to generate the DMG files myself but I'm back to the same point above, leveraging tools/code that is already there is a better use of my time. 

The 3 types of output like a decent idea, I suppose technically it's a single output format from the core, JSON.  

This then gets fed to a formatter, of which there would be 3, NullFormatter, JSONFormatter, HumanFormatter (for want of better names) that take the JSON and produce the relevant output (or not in the case of the NullFormatter which would just eat it, the JSON Formatter would pipe it through and the HumanFormatter would produce human readable output from the JSON), it would also give scope to add other output formatters if somebody so desired/had the need.

**Comment by al45tair** [comment]
> My rational is that I went with the ribbon bar specifically because it's a design paradigm that has successfully transferred from Windows to Mac

:-D We'll have to agree to disagree on that. FWIW, while they don't use the default Cocoa UI, Affinity and Logic Pro are certainly Mac-like (as is all of Adobe's software). CLion, Excel and VSCode look out of place on the Mac IMO, though I appreciate they're not alone, and sticking a Windows-style ribbon on a Mac app is just weird. :-)

> Of course this particular application is Mac only because of the reliance on tools such as hdiutil, I could however invest time in writing code to generate the DMG files myself

It might be fun at some point to do that, but I think it's a non-trivial amount of work.

> The 3 types of output like a decent idea, I suppose technically it's a single output format from the core, JSON.

Well, the core will presumably not use JSON, but rather Python objects. Then yes, as you say, you'd have three formatters.

**Comment by fizzyade** [comment]
I can always hide the ribbon bar with a single line of code ;). I will also admit, that when the ribbon bar first came into use I wasn't a huge fan, but my view on that has changed over the years, possibly because from a design perspective I've seen what a difference it can make to the end users experience, I appreciate that what works for one person might not work for another.

I'm going to have a good look through your code and then figure out a plan of attack, whatever I do I want to make sure that it compliments your existing code without making anything confusing.

**Comment by fizzyade** [comment]
> > My rational is that I went with the ribbon bar specifically because it's a design paradigm that has successfully transferred from Windows to Mac
> 
> :-D We'll have to agree to disagree on that. FWIW, while they don't use the default Cocoa UI, Affinity and Logic Pro are certainly Mac-like (as is all of Adobe's software). CLion, Excel and VSCode look out of place on the Mac IMO, though I appreciate they're not alone, and sticking a Windows-style ribbon on a Mac app is just weird. :-)
> 
> > Of course this particular application is Mac only because of the reliance on tools such as hdiutil, I could however invest time in writing code to generate the DMG files myself
> 
> It might be fun at some point to do that, but I think it's a non-trivial amount of work.
> 
> > The 3 types of output like a decent idea, I suppose technically it's a single output format from the core, JSON.
> 
> Well, the core will presumably not use JSON, but rather Python objects. Then yes, as you say, you'd have three formatters.

Ok, I've just had a little play, just wondering on your thoughts before I get too ahead of myself and implement something that is not along the lines you were thinking.

Basically, I have added a callback parameter to dmgbuild.build_dmg (defaults to quiet_callback if no callback is supplied which does not output anything).

```python

def quiet_callback(info):
    pass

    ....

def build_dmg(filename, volume_name, settings_file=None, settings={},
    defines={}, lookForHiDPI=True, detach_retries=5, callback=quiet_callback):
    ....

    callback({'type': 'command::start', 'command': 'hdiutil::create', 'total_size': total_size})

    ret, output = hdiutil('create',
                          '-ov',
                          '-volname', volume_name,
                          '-fs', 'HFS+',
                          '-fsargs', '-c c=64,a=16,e=16',
                          '-size', total_size,
                          writableFile.name)

    callback({'type':'command::result', 'command': 'hdiutil::create', 'ret': ret, 'output': output})

    ....

dmgbuild.build_dmg('/tmp/out.dmg', 'Test', 'examples/settings.py', callback=my_callback)
```

Other things:

* Human readable description as well?
* Progress value, although need to think about this as any changes to the script would require making sure that the existing stages are adjusted.  This would allow a progress bar to be displayed.

**Comment by fizzyade** [comment]
Here's an example output (bearing in mind that this fails due to unflatten/flatten verbs not being present in hditool in macOS 11 - I've opened another issue regarding that)

you provide a callback function which receives a dictionary, the type field tells you what is currently happening, the type has a '::' delimiter to further granulise the message.

```
build
operation
command
```

build:
```
started -> (build::started)
finished -> (build::finished)
````

operation:
```
start -> operation::start
finished -> operation::finished
```

operation adds a dictionary entry named operation, this has a value which tells you which operation is being performed, i.e
```
background::create
settings::load
size::calculate
files::add
file::add
symlinks::add
symlink::add
extensions::hide
dmg::addlicense
```
each operation may include other fields in the dictionary to provide further information, for example file::add has a file dictionary entry which indicates the file being processed.

When an external command is called (i.e hditool), the callback supplies a command message.

```
command::start
command::finished
```

command::finished has a ret dictionary entry which contains the return code of the command, and an output key which contains any output from the command.

This looks like it will work for me, I can use the information from the output to produce a nice output from the tool which gives me progress and feedback on the state of the build.


```
{'type': 'build::started'}
{'type': 'operation::start', 'operation': 'settings::load'}
{'type': 'operation::finished', 'operation': 'settings::load'}
{'type': 'operation::start', 'operation': 'size::calculate'}
{'type': 'operation::finished', 'operation': 'size::calculate', 'size': '137060.352K'}
{'type': 'command::start', 'command': 'hdiutil::create'}
{'type': 'command::finished', 'command': 'hdiutil::create', 'ret': 0, 'output': ['/private/tmp/.tempv6rzvnqkout.dmg']}
{'type': 'command::start', 'command': 'hdiutil::attach'}
{'type': 'command::finished', 'command': 'hdiutil::create', 'ret': 0, 'output': {'system-entities': [{'content-hint': 'Apple_HFS', 'dev-entry': '/dev/disk2s1', 'mount-point': '/Volumes/Test', 'potentially-mountable': True, 'unmapped-content-hint': '48465300-0000-11AA-AA11-00306543ECAC', 'volume-kind': 'hfs'}, {'content-hint': 'GUID_partition_scheme', 'dev-entry': '/dev/disk2', 'potentially-mountable': False, 'unmapped-content-hint': 'GUID_partition_scheme'}]}}
{'type': 'operation::start', 'operation': 'dmg::create'}
{'type': 'operation::start', 'operation': 'background::create'}
{'type': 'operation::finished', 'operation': 'background::create'}
{'type': 'operation::start', 'operation:': 'files::add'}
{'type': 'operation::start', 'operation': 'file::add', 'file:': '/Volumes/Test/Stickies.app'}
{'type': 'operation::finished', 'operation': 'file::add', 'file:': '/Volumes/Test/Stickies.app'}
{'type': 'operation::finished', 'operation:': 'files::add'}
{'type': 'operation::start', 'operation:': 'symlinks::add'}
{'type': 'operation::start', 'operation': 'symlink::add', 'file:': '/Volumes/Test/Applications'}
{'type': 'operation::finished', 'operation': 'symlink::add', 'file:': '/Volumes/Test/Applications'}
{'type': 'operation::finished', 'operation:': 'symlinks::add'}
{'type': 'operation::start', 'operation:': 'extensions::hide'}
{'type': 'operation::finished', 'operation:': 'extensions::hide'}
{'type': 'operation::start', 'operation': 'dsstore::create'}
{'type': 'operation::finished', 'operation': 'dsstore::create'}
{'type': 'operation::finished', 'operation': 'dmg::create'}
{'type': 'command::start', 'command': 'hdiutil::detach'}
ditto: /Volumes/Test/Stickies.app/Contents: Operation not permitted
{'type': 'command::finished', 'command': 'hdiutil::detach', 'ret:': 0, 'output:': b'"disk2" ejected.\n'}
{'type': 'command::start', 'command': 'hdiutil::resize'}
{'type': 'command::finished', 'command': 'hdiutil::resize', 'ret': 0, 'output': b''}
{'type': 'operation::start', 'operation': 'dmg::shrink'}
{'type': 'command::start', 'command': 'hdiutil::convert'}
{'type': 'command::finished', 'command': 'hdiutil::convert', 'ret': 0, 'output': ['/tmp/out.dmg']}
{'type': 'operation::finished', 'operation': 'dmg::shrink'}
{'type': 'operation::start', 'command': 'dmg::addlicense'}
{'type': 'command::start', 'command': 'hdiutil::unflatten'}
hdiutil: unflatten: verb not recognized
Usage: /usr/bin/hdiutil <verb> <options>
<verb> is one of the following:
help
attach
detach
eject
verify
create
compact
convert
burn
info
checksum
chpass
erasekeys
imageinfo
isencrypted
makehybrid
mount
mountvol
unmount
plugins
resize
segment
pmap
udifderez
udifrez
{'type': 'command::finished', 'command': 'hdiutil::unflatten', 'ret': 1, 'output': b''}
Unable to unflatten to add license

Process finished with exit code 1

```

**Comment by fizzyade** [comment]
PR here: https://github.com/al45tair/dmgbuild/pull/30

**Comment by al45tair** [comment]
I've merged the PR.
