### ISSUE TITLE
Implement __main__ for dmgbuild?

### ISSUE THREAD

**Issue by phargogh** [al45tair/dmgbuild#28]
Thanks so much for such a useful tool!

I'm working on a project where we'd like to be able to switch out the python interpreter used for the `dmgbuild` CLI entrypoint, and I see that the package doesn't have an implemented `dmgbuild.__main__`.  I wouldn't want to step on anyone's toes or get in the way of any existing plans, but I'd be very happy to implement this for you and submit a PR if this sounds like a useful feature to you!  Would this be a useful addition?

**Comment by al45tair** [comment]
I'm not entirely sure what you mean here. Are you saying that you'd like the argument parsing code currently in `scripts/dmgbuild` to be in a new `dmgbuild/main.py` file and then just have the script call it?

Maybe I'm missing something, but I don't see a huge benefit in that. If you're after programmatic access to dmgbuild, you'd import the package and call the `dmgbuild.build_dmg()` function directly.

**Comment by phargogh** [comment]
Sorry for the delay here!

The thing I'm hoping to do would be to `python -m dmgbuild <args>`.  This would allow me to specify the python interpreter in the shell script and use the command-line interface as usual.  IThis would be functionally similar to `python -c "import dmgbuild; dmgbuild.build_dmg(...)"`, as you suggested, just without needing to know the python function parameters and the order they are required to be in.

I've put together a demo (here's the [comparison](https://github.com/al45tair/dmgbuild/compare/master...phargogh:feature/28-implement-module-entrypoint)) of what this might look like in the package.

Note that this approach should still expose the `dmgbuild` CLI entrypoint as you had before, this would just also support calling the package via `python -m dmgbuild`.

**Comment by al45tair** [comment]
I've turned your diff into a PR. Assuming it passes the tests, I'll merge it.

**Comment by phargogh** [comment]
Thanks!

**Comment by al45tair** [comment]
All merged now. I'll do one final release soon (I can't work on dmgbuild any more as of Tuesday…)
