### ISSUE TITLE
v1.4.2 tag commit not on master branch

### ISSUE THREAD

**Issue by speleo3** [al45tair/dmgbuild#31]
The `v1.4.2` tag is one commit ahead of the master branch. I assume that's not intentional.

Commit: https://github.com/al45tair/dmgbuild/commit/296990e8817bf87fbdf48c2e4dad5c136e1e3df5

Warning shown by github:

![screenshot](https://user-images.githubusercontent.com/1239490/99502545-82f9ec80-297d-11eb-90c3-d980aca60748.png)

**Comment by al45tair** [comment]
Oops, no, it wasn't intentional. Fixed.
