### ISSUE TITLE
New maintainer wanted.

### ISSUE THREAD

**Issue by al45tair** [al45tair/dmgbuild#38]
dmgbuild will need a new maintainer as I'm starting at Apple on the 1st (and that pretty much precludes working on Open Source, for now). Please get in touch if you're using dmgbuild and you're interested in taking it over.

**Comment by freakboy3742** [comment]
Hi - I'm currently using dmgbuild as part of [Briefcase](https://github.com/beeware/briefcase); I've got a (small) history of contributing to the project (#20). I'd be happy to take on the maintainer role if you'd like.

**Comment by ann0see** [comment]
@freakboy3742 If I were you, I'd ping the old maintainer again or fork the repo. We've moved to another script, but would still very much appreciate if this didn't die.

**Comment by freakboy3742** [comment]
@al45tair Repeating the offer; I've got a (small) history of contributing to the project (https://github.com/al45tair/dmgbuild/issues/20). I'd be happy to take on the maintainer role if you'd like.

**Comment by al45tair** [comment]
@freakboy3742 Sorry, I'd been quite busy and I had had a couple of offers from people at Big Tech companies who indicated that they might be able to take it on with some official support, but none of them have actually got back to me about it since. I've added you to the repo, and will see what I can do on the PyPi end — I assume you have a PyPi account?

**Comment by al45tair** [comment]
@freakboy3742 Found your PyPi account. I've also invited you to the two projects this relies on (https://github.com/al45tair/mac_alias and https://github.com/al45tair/ds_store) and added you as a maintainer of all three of them on PyPi.

**Comment by al45tair** [comment]
@freakboy3742 If you're happy, I think we can close this issue now?
