### ISSUE TITLE
Python 3 compatibility updates broke compatibility with older Python versions

### ISSUE THREAD

**Issue by jakepetroules** [al45tair/dmgbuild#4]
In [Qbs](/qbs/qbs) we still aim to support some older versions of macOS. The versions of Python available by default on macOS are:

- Mac OS X Lion (10.7.5) - Python 2.7.1
- OS X Mountain Lion (10.8.5) - Python 2.7.2
- OS X Mavericks (10.9.5) - Python 2.7.5
- OS X Yosemite (10.10.5) to macOS High Sierra (10.13.x) - Python 2.7.10

Instead of testing only Python 2.7.13, we should either test 2.7.0 or test each of the Python 2.7.x versions available as defaults on all macOS versions.

The latest Python 3 compatibility changes broke our build on macOS 10.9.5. The current Travis integration also doesn't seem to actually test much of anything since it only installs dmgbuild but never actually runs it.

The error we encountered is:

```
ERROR: Traceback (most recent call last):
  File "/Users/berlin/jenkins/workspace/qbs-mac-1.9/label/ubermac/Schattenbau/libexec/qbs/dmgbuild", line 36, in <module>
    dmgbuild.build_dmg(args.filename, args.volume_name, args.settings, defines=defines, lookForHiDPI=args.lookForHiDPI)
  File "/Users/berlin/jenkins/workspace/qbs-mac-1.9/label/ubermac/Schattenbau/share/qbs/python/dmgbuild/core.py", line 537, in build_dmg
    d['.']['pBBk'] = background_bmk
  File "/Users/berlin/jenkins/workspace/qbs-mac-1.9/label/ubermac/Schattenbau/share/qbs/python/ds_store/store.py", line 1237, in __setitem__
    entry_type, entry_value))
  File "/Users/berlin/jenkins/workspace/qbs-mac-1.9/label/ubermac/Schattenbau/share/qbs/python/ds_store/store.py", line 732, in insert
    self._insert_leaf(path, node, entry)
  File "/Users/berlin/jenkins/workspace/qbs-mac-1.9/label/ubermac/Schattenbau/share/qbs/python/ds_store/store.py", line 695, in _insert_leaf
    if remaining < entry.byte_length():
  File "/Users/berlin/jenkins/workspace/qbs-mac-1.9/label/ubermac/Schattenbau/share/qbs/python/ds_store/store.py", line 202, in byte_length
    value = self.type.encode(self.value)
  File "/Users/berlin/jenkins/workspace/qbs-mac-1.9/label/ubermac/Schattenbau/share/qbs/python/ds_store/store.py", line 48, in encode
    return bmk.to_bytes()
  File "/Users/berlin/jenkins/workspace/qbs-mac-1.9/label/ubermac/Schattenbau/share/qbs/python/mac_alias/bookmark.py", line 512, in to_bytes
    for k,o in entries])))
TypeError: Struct() argument 1 must be string, not unicode
```

**Comment by al45tair** [comment]
You're quite right that the current tests are rather limited in scope. It _does_ run the dmgbuild code, however — take a look at `test_samples.py` — but it would be good to add more tests, particularly in the `mac_alias` and `ds_store` projects.

**Comment by jakepetroules** [comment]
Ah, my mistake. Looking at the code, the failing path *should* be triggered by the CI but it still succeeded with 2.7.0. I wonder if this is specific to exactly version 2.7.5... testing now with #5.

**Comment by al45tair** [comment]
FWIW, there's no need to create pull requests to get the tests to run — you can run the tests locally using

    python setup.py test

You could use pyenv to install the versions of Python you care about.

**Comment by jakepetroules** [comment]
Can you please check #5 and get those build failures fixed?

**Comment by al45tair** [comment]
Looks like a missing `b` on the `struct.pack()` format string in `bookmark.py` in `mac_alias`. Frustratingly, Python behaviour in that case can be quite inconsistent. I've fixed `mac_alias`, released an update and restarted the failed builds.

**Comment by jakepetroules** [comment]
This is possibly due to https://bugs.python.org/issue19099 which was "fixed" in 2.7.7. At first I thought it was a regression because strangely it doesn't seem to affect 2.7.0 or 2.7.1.

**Comment by al45tair** [comment]
Hmmm. OK, well it's all working _except_ that for some reason when it tries to use Python 2.7.1, it's actually testing with 2.7.12. The other versions all work as expected, so that's a bit of a puzzle.

**Comment by al45tair** [comment]
OK, I think this is now fixed.

**Comment by jakepetroules** [comment]
Tagged releases, please? :)

**Comment by jakepetroules** [comment]
Actually, it seems that the mac_alias 2.0.6 on pypi is identical to the 2.0.4 version... can you please check on that?

**Comment by al45tair** [comment]
No, it's definitely different (look at Bookmark.from_bytes).

**Comment by jakepetroules** [comment]
I was installing a local copy of the modules like so:

    pip install -U --isolated --prefix=$PWD --no-binary :all: --no-compile --no-deps biplist dmgbuild ds_store mac_alias

Maybe it wasn't overwriting the already-existing directories?

**Comment by al45tair** [comment]
How odd. I just downloaded the tar file to check, and it's definitely based on the v2.0.6 tag, so you're right there must have been some other oddity.

**Comment by jakepetroules** [comment]
Do you know what options I should be passing to pip to force it to upgrade the installed package? It seems that no matter what I do, it refuses to update mac_alias from the existing 2.0.4 to 2.0.6. Even though the output shows the right version:

```
Collecting biplist
  Downloading biplist-1.0.2.tar.gz
Collecting dmgbuild
  Downloading dmgbuild-1.3.1.tar.gz
Collecting ds_store
  Downloading ds_store-1.1.2.tar.gz
Collecting mac_alias
  Downloading mac_alias-2.0.6.tar.gz
Installing collected packages: biplist, dmgbuild, ds-store, mac-alias
  Running setup.py install for biplist ... done
  Running setup.py install for dmgbuild ... done
  Running setup.py install for ds-store ... done
  Running setup.py install for mac-alias ... done
Successfully installed biplist-1.0.2 dmgbuild-1.3.1 ds-store-1.1.2 mac-alias-2.0.6
```

**Comment by al45tair** [comment]
The options look correct. Are you sure you haven't somehow ended up installing it somewhere else? Have you ever installed it using `setup.py`? In particular, `setup.py develop` often seems to result in my having multiple versions of things installed.

You could try doing

    pip uninstall mac_alias

until it says it isn't installed any more.

**Comment by al45tair** [comment]
Oh, I see. Sorry, I hadn't noticed that part. Why don't you use `virtualenv` and then you can use normal `pip install`?

**Comment by jakepetroules** [comment]
We include a local copy of the modules (https://github.com/qbs/qbs/tree/1.9/src/3rdparty/python) and install it in our app's share/ directory; this seemed to be the easiest way to do it.
