### ISSUE TITLE
Include a .command file in the dmg causes a python error

### ISSUE THREAD

**Issue by alby128** [al45tair/dmgbuild#8]
I am trying to include a .command script in a packaging dmg using dmgbuild, but I get a python error during the packaging and no resulting dmg file.

I run dmgbuild with: 
`dmgbuild -s appdmg.py "AppName" appcontainer.dmg`

In the appdmg.py file there are (among others) the following lines:
```
files = [ application, 'resources/lua/intf/script.lua', 'resources/install.command' ]

symlinks = { 'Applications': '/Applications' }

icon_locations = {
    appname:        (80, 80),
    'Applications': (280, 80),
    'script.lua': (80, 240),
    'install.command': {280, 240}
}
```

The error that I get is:

> Traceback (most recent call last):
>   File "/usr/local/bin/dmgbuild", line 36, in <module>
>     dmgbuild.build_dmg(args.filename, args.volume_name, args.settings, defines=defines, lookForHiDPI=args.lookForHiDPI)
>   File "/usr/local/lib/python2.7/site-packages/dmgbuild/core.py", line 543, in build_dmg
>     d[k]['Iloc'] = v
>   File "/usr/local/lib/python2.7/site-packages/ds_store/store.py", line 1237, in __setitem__
>     entry_type, entry_value))
>   File "/usr/local/lib/python2.7/site-packages/ds_store/store.py", line 732, in insert
>     self._insert_leaf(path, node, entry)
>   File "/usr/local/lib/python2.7/site-packages/ds_store/store.py", line 695, in _insert_leaf
>     if remaining < entry.byte_length():
>   File "/usr/local/lib/python2.7/site-packages/ds_store/store.py", line 202, in byte_length
>     value = self.type.encode(self.value)
>   File "/usr/local/lib/python2.7/site-packages/ds_store/store.py", line 25, in encode
>     return struct.pack(b'>IIII', point[0], point[1],
> TypeError: 'set' object does not support indexing
> 

Everything works perfectly if I remove the references to the .command file. I am running dmgbuild on Python 2.7.13 on macOS 10.12.6.

**Comment by al45tair** [comment]
It's because you've written {280, 240} rather than (280, 240). Fix that and it should work.

**Comment by alby128** [comment]
Whoops, sorry, my fault. Another (probably dumb) question: it is possible to hide the extension in the .command file included in this way in the .dmg? Thanks.

**Comment by alby128** [comment]
@al45tair Whoops, sorry, my fault. Another (probably dumb) question: it is possible to hide the extension in the .command file included in this way in the .dmg? Thanks.

**Comment by al45tair** [comment]
On 27 Sep 2017, at 16:21, Alberto Sottile <notifications@github.com> wrote:
> 
> Whoops, sorry, my fault. Another (probably dumb) question: it is possible to hide the extension in the .command file included in this way in the .dmg? Thanks.

Yes, it’s possible, but I don’t think I built anything into dmgbuild to do it.  Probably the best thing is to file a separate issue asking for that as a feature.  I can’t guarantee I’ll have the time to look at it any time soon, but if it’s in there then I’m likely to get to it at some point.

Kind regards,

Alastair.

--
http://alastairs-place.net
