### ISSUE TITLE
Hide extension in the included files [Feature request]

### ISSUE THREAD

**Issue by albertosottile** [al45tair/dmgbuild#9]
I would like to hide the extension in any of the files included in the bundled .dmg. macOS automatically hides the extension of the .app file, but dmgbuild does not do that automatically for all the embedded files. Currently, it is not possible to select which files show they extension and which do not. This would be a nice feature, especially if someone wants to include scripts with long .command extensions.

As a workaround, it is currently possible to eliminate the extension by hiding the file (by adding a . before its name), including it in the .dmg, and then creating a symlink using "symlinks:" that points on the hidden file. The created symlink can have an arbitrary name without any extension. The hidden file will not appear in the created .dmg as expected.

**Comment by al45tair** [comment]
On 27 Sep 2017, at 22:46, Alberto Sottile <notifications@github.com> wrote:
> 
> I would like to hide the extension in any of the files included in the bundled .dmg. macOS automatically hides the extension of the .app file, but dmgbuild does not do that automatically for all the embedded files. Currently, it is not possible to select which files show they extension and which do not. This would be a nice feature, especially if someone wants to include scripts with long .command extensions.
> 
> As a workaround, it is currently possible to hide the file by adding a . before its name, include it in the .dmg, and then create a symlink using "symlinks:" that points on the hidden file. The created symlink can have an arbitrary name without any extension. The hidden file will not appear in the created .dmg as expected.

It’s probably also worth mentioning, in the context of the file you wanted to hide the extension of, that you don’t need to name something “.command” to get it to run in Terminal.  If you start the file with

  #! /bin/sh

or

  #! /bin/bash

and then make sure its “x” bit(s) are set, you can call it whatever you like.

Kind regards,

Alastair.

--
http://alastairs-place.net

**Comment by albertosottile** [comment]
Thanks for having implemented this!
